In [1]:
import numpy as np
import time

import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [3]:
probabilites = torch.tensor([0.1, 0.4, 0.5]) # they should always end up being equal to 1
# there is 10% chance of getting 0, 40% chance of getting 1 and 50% chance of getting 2. 
# Meaning that we have probability of getting the corresponding index.
samples = torch.multinomial(probabilites, num_samples=10, replacement=True)
print(samples)

# This concept will be used for getting the probabilities for next character prediction. 

tensor([0, 2, 0, 1, 1, 1, 2, 1, 1, 2])


In [6]:
# Concatenation
first_tensor = torch.tensor([1, 2, 3, 4, 5])
concatenated_tensor = torch.concatenate((first_tensor, torch.tensor([6, 7, 8, 9, 10])), axis=0)
print(concatenated_tensor)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [8]:
triangular_lower = torch.tril(torch.ones(8,8))
print(triangular_lower)

# This will be used for setting the predictions that we have made. 
# Meaning, we have the first token (already set to 1) but rest of them have to predicted so they are set as 0. 
# As we move forward, we make predictions and consequtively set them to 1. 
# This makes sure that we do not interact with the future!

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])


In [9]:
# Similar to the previous case, we have
triangular_upper = torch.triu(torch.ones(8,8))
print(triangular_upper)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 1.]])


In [12]:
# So, this is one of the most important concepts for biagram model. We exponentiate our tensors.
exp_triang_lower = torch.zeros(8,8).masked_fill(torch.tril(torch.ones(8,8))==0, float('-inf'))
print(exp_triang_lower)

# When we raise the tensor with exp. 
# e^{-inf} = 1; e^{0} = 1
print(torch.exp(exp_triang_lower))

tensor([[0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., 0., -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0., 0., 0., 0.]])
tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])


In [19]:
# Yet another simple function
zeros_tensor = torch.zeros((5, 2, 3))
transponsed_zeros_tensor = zeros_tensor.transpose(0, 2)
print(transponsed_zeros_tensor.shape)

torch.Size([3, 2, 5])


In [20]:
# Looking at quite an inportant function: `torch.stack`
# We need this for parallel processing where we stack multiple blocks with fixed length (no. of tokens)
tensor_1 = torch.tensor([1, 2, 3])
tensor_2 = torch.tensor([4, 5, 6])
tensor_3 = torch.tensor([7, 8, 9])

stacked_tensor = torch.stack((tensor_1, tensor_2, tensor_3))
print(stacked_tensor)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [29]:
# Simple neural network
import torch.nn as nn
import torch.nn.functional as F
input_tensor = torch.tensor([2., 3., 4]) # takes float
linear_layer = nn.Linear(in_features=3, out_features=4, bias=False) # can change the output features but not the input
output_tensor = linear_layer(input_tensor)
print(output_tensor)

# Lets try to store the output and then apply the activation function
out_after_act = F.softmax(output_tensor, dim=0)
print(out_after_act)

tensor([-1.3292, -0.2261, -1.2684,  1.5387], grad_fn=<SqueezeBackward3>)
tensor([0.0441, 0.1329, 0.0469, 0.7761], grad_fn=<SoftmaxBackward0>)
